### ISSUE TITLE
When Tern executes fs_hash.sh, it cannot cd to the contents directory.

### ISSUE THREAD

**Issue by Katsunori04** [vmware/tern#430] opened 2019-08-30 07:07 UTC
Hello, Tern Team.
When I tried to analyze the "yarara / base: v1" image, Tern output the following error.
Tern can't use command's "cd".
Is it my environmental problem or the Tern specification problem?

**Problem Statement**
When Tern executes fs_hash.sh, it cannot cd to the contens directory.

**To Reproduce**
```
vagrant@ubuntu-bionic:~$ tern -l  -k report -i yarara/base:v1
fatal: not a git repository (or any of the parent directories): .git
2019-08-30 06:46:33,865 - DEBUG - __main__ - Starting...
2019-08-30 06:46:33,866 - DEBUG - report - Setting up...
2019-08-30 06:46:33,866 - DEBUG - container - Checking if image "yarara/base:v1" is available on disk...
2019-08-30 06:46:33,871 - DEBUG - container - Attempting to pull image "yarara/base:v1"
2019-08-30 06:46:56,728 - DEBUG - container - Image "yarara/base:v1" downloaded
2019-08-30 06:47:05,844 - DEBUG - rootfs - Running command: sudo /usr/local/lib/python3.6/dist-packages/tern/tools/fs_hash.sh /home/vagrant/temp/3bf9dc6ca1042e8f1e9ce7b6a62bbe1ea0c224323b6fbc34e5e5e35905cd4206/contents
2019-08-30 06:47:08,952 - ERROR - rootfs - Command failed. /usr/local/lib/python3.6/dist-packages/tern/tools/fs_hash.sh: 22: cd: can't cd to /home/vagrant/temp/3bf9dc6ca1042e8f1e9ce7b6a62bbe1ea0c224323b6fbc34e5e5e35905cd4206/contents

2019-08-30 06:47:08,953 - WARNING - report - Cannot retrieve full image metadata
2019-08-30 06:47:08,953 - DEBUG - report - Teardown...
2019-08-30 06:47:08,954 - DEBUG - rootfs - Running command: sudo rm -rf temp/mergedir
2019-08-30 06:47:08,965 - DEBUG - rootfs - Running command: sudo rm -rf temp/workdir
2019-08-30 06:47:08,975 - DEBUG - __main__ - Report completed.
2019-08-30 06:47:08,976 - DEBUG - __main__ - Finished
```

**Comment by nishakm** [comment] 2019-08-30 12:57
Hello!

Thanks for trying tern out! I can recreate this issue and will debug it today. Would you mind filing an issue on GitHub for this?

Nisha Kumar
Open Source Engineer
VMware Open Source Technology Center




On Aug 30, 2019, at 12:07 AM, Katsunori Fukui <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello, Tern Team.
When I tried to analyze the "yarara / base: v1" image, Tern output the following error.
Tern can't use command's "cd".
Is it my environmental problem or the Tern specification problem?

Problem Statement
When Tern executes fs_hash.sh, it cannot cd to the contens directory.

To Reproduce
`
vagrant@ubuntu-bionic:~$ tern -l -k report -i yarara/base:v1
fatal: not a git repository (or any of the parent directories): .git
2019-08-30 06:46:33,865 - DEBUG - main - Starting...
2019-08-30 06:46:33,866 - DEBUG - report - Setting up...
2019-08-30 06:46:33,866 - DEBUG - container - Checking if image "yarara/base:v1" is available on disk...
2019-08-30 06:46:33,871 - DEBUG - container - Attempting to pull image "yarara/base:v1"
2019-08-30 06:46:56,728 - DEBUG - container - Image "yarara/base:v1" downloaded
2019-08-30 06:47:05,844 - DEBUG - rootfs - Running command: sudo /usr/local/lib/python3.6/dist-packages/tern/tools/fs_hash.sh /home/vagrant/temp/3bf9dc6ca1042e8f1e9ce7b6a62bbe1ea0c224323b6fbc34e5e5e35905cd4206/contents
2019-08-30 06:47:08,952 - ERROR - rootfs - Command failed. /usr/local/lib/python3.6/dist-packages/tern/tools/fs_hash.sh: 22: cd: can't cd to /home/vagrant/temp/3bf9dc6ca1042e8f1e9ce7b6a62bbe1ea0c224323b6fbc34e5e5e35905cd4206/contents

2019-08-30 06:47:08,953 - WARNING - report - Cannot retrieve full image metadata
2019-08-30 06:47:08,953 - DEBUG - report - Teardown...
2019-08-30 06:47:08,954 - DEBUG - rootfs - Running command: sudo rm -rf temp/mergedir
2019-08-30 06:47:08,965 - DEBUG - rootfs - Running command: sudo rm -rf temp/workdir
2019-08-30 06:47:08,975 - DEBUG - main - Report completed.
2019-08-30 06:47:08,976 - DEBUG - main - Finished
`

**Comment by nishakm** [comment] 2019-08-30 15:25
Python3.7's `tarfile` module will not extract these layers.

**Comment by PrajwalM2212** [comment] 2019-08-30 15:38
Yes, `tar.extractall(directory_path)` is raising the error.

**Comment by nishakm** [comment] 2019-08-30 15:41
@Katsunori04 it looks like the image you are using is corrupted. See tar error below.

```
vagrant@ubuntu-bionic:~/temp/1b73c719e179f6a7702a653f2753c4ab459d5e379a483d6ce8888104f5c1ae1c$ tar xvf layer.tar 
./
.wh..wh.aufs
.wh..wh.orph/
.wh..wh.plnk/
dev/
dev/ptmx
etc/
etc/apt/
etc/apt/apt.conf.d/
etc/apt/apt.conf.d/no-cache
etc/apt/apt.conf.d/no-languages
etc/dpkg/
etc/dpkg/dpkg.cfg.d/
etc/dpkg/dpkg.cfg.d/02apt-speedup
sbin/
sbin/initctl
sbin/initctl.distrib
usr/
usr/sbin/
usr/sbin/policy-rc.d
var/
var/lib/
var/lib/dpkg/
var/lib/dpkg/diversions
var/lib/dpkg/diversions-old
var/lib/dpkg/status
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
```

What happened was that the first layer that tern hit was an empty tarfile, and because of this, tar exited with no error but because nothing was extracted it failed.
We have a bug being worked on that checks tarfile elements before extracting: https://github.com/vmware/tern/issues/226.

Meanwhile, I think the image you have used is corrupted.

**Comment by nishakm** [comment] 2019-08-30 15:42
> Yes, `tar.extractall(directory_path)` is raising the error.
> I had got the extraction error for another image as well but was not sure if it was related to this but now we now that tarfile module is the source of error.

What was the other image you used?

**Comment by PrajwalM2212** [comment] 2019-08-30 15:55
@nishakm ubuntu:14.04

**Comment by nishakm** [comment] 2019-08-30 16:22
OK, the issue with the `ubuntu:14.04` is a permissions issue rather than a tarball extraction issue. So closing this one.

**Closed by nishakm** 2019-08-30 16:22 UTC
Labels: bug

**Comment by Katsunori04** [comment] 2019-08-30 16:54
Thank you so much. I feel that the image is damaged. I didn't notice.
I also found similar errors in other images.

I feel this is not a corruption error. However, the contents of the tarfile are missing. Is this issue affected by # 226?

**To Reproduce**
'''
vagrant@ubuntu-bionic:~$ tern -l -k report -i nubs/arch-build:latest
fatal: not a git repository (or any of the parent directories): .git
2019-08-30 16:41:21,882 - DEBUG - __main__ - Starting...
2019-08-30 16:41:21,883 - DEBUG - report - Setting up...
2019-08-30 16:41:21,913 - DEBUG - container - Checking if image "nubs/arch-build:latest" is available on disk...
2019-08-30 16:41:21,919 - DEBUG - container - Image "nubs/arch-build:latest" found
2019-08-30 16:42:21,245 - DEBUG - rootfs - Running command: sudo /usr/local/lib/python3.6/dist-packages/tern/tools/fs_hash.sh /home/vagrant/temp/3bf9dc6ca1042e8f1e9ce7b6a62bbe1ea0c224323b6fbc34e5e5e35905cd4206/contents
2019-08-30 16:42:59,468 - ERROR - rootfs - Command failed. /usr/local/lib/python3.6/dist-packages/tern/tools/fs_hash.sh: 22: cd: can't cd to /home/vagrant/temp/3bf9dc6ca1042e8f1e9ce7b6a62bbe1ea0c224323b6fbc34e5e5e35905cd4206/contents

2019-08-30 16:42:59,469 - WARNING - report - Cannot retrieve full image metadata
2019-08-30 16:42:59,469 - DEBUG - report - Teardown...
2019-08-30 16:42:59,485 - DEBUG - rootfs - Running command: sudo rm -rf temp/mergedir
2019-08-30 16:42:59,494 - DEBUG - rootfs - Running command: sudo rm -rf temp/workdir
2019-08-30 16:42:59,505 - DEBUG - __main__ - Report completed.
2019-08-30 16:42:59,505 - DEBUG - __main__ - Finished
'''

**Comment by nishakm** [comment] 2019-08-30 17:16
@Katsunori04 I'm not sure about the status of the images you are testing here, but if the contents of the tarfile are missing, tern can't give you any information anyway.
