### ISSUE TITLE
Isolate docker functionality into it's own analysis module

### ISSUE THREAD

**Issue by nishakm** [vmware/tern#262] opened 2019-05-13 14:02 UTC
**Problem Statement**
Currently Tern only supports docker-related analysis. In the future, however, there might be different types of container formats that we would also like to support. In order to make this integration easier in the future, we should separate docker reporting from other types of potential reporting.

The analysis code for a container image is all in one module `report.py`. We should separate any docker-related anaylsis into its own module. 

**Describe the Proposal**
Separate docker reporting from other types of potential reporting by refactoring analysis-related code into its own module.

**Steps to Implement Proposal**
1. Make new module `tern/analyze/docker`
2. Move all docker-related code into that
3. Refactor accordingly

**Comment by PrajwalM2212** [comment] 2019-08-29 16:00
This may have been a duplicate of https://github.com/vmware/tern/issues/212

**Comment by nishakm** [comment] 2019-08-29 16:19
No, we want to be able to detach generating the report from analyzing the image. There are actually several steps needed to do this, one of them being #212.
1. Create analyze folder with its own __init__.py so now it's a module
2. Move analyze.py to that module
3. Separate the Dockerfile building and mapping from the raw image analysis
4. Create a place for container image plugins for functions like `pull`, `list` and `save`

Our ultimate goal with this is to allow other OCI compatible images (which Docker images are not) to also be analyzed.

**Comment by rnjudge** [comment] 2020-02-04 23:39
@nishakm I think we can close this, would you agree? `tern/analyze/docker` exists with the docker code generally separated.

**Comment by nishakm** [comment] 2020-02-05 01:00
@rnjudge Some related code exists in other places and I am yet to do curation of it. Probably the best option is to file a bug as I come across them. So yeah, I think we can close this one for now.

**Closed** 2020-02-05 16:48 UTC
Labels: proposal, refactor, super, technical-debt
