### ISSUE TITLE
Receiving Failed to Synchronize Cache for Repo errors when running docker build after gitclone.  

### ISSUE THREAD

**Issue by bmalinow** [vmware/tern#623] opened 2020-04-01 14:37 UTC
**Describe the bug**

**To Reproduce**
1. Go to https://github.com/vmware/tern#getting-started-with-docker
2. Run the first step to git clone the repo to local. Navigate to /tern/ directory.
3. Run the following command from step 2 (Build the Docker image) 
`docker build -t ternd .`

**Error in terminal**
```
$ docker build -t ternd .
Sending build context to Docker daemon  10.29MB
Step 1/6 : FROM photon:3.0
 ---> 63da4c9ea81a
Step 2/6 : RUN tdnf remove -y toybox && tdnf install -y tar findutils attr util-linux python3 python3-pip python3-setuptools git
 ---> Running in 8b0473962454
curl#7: Couldn't connect to server
Error: Failed to synchronize cache for repo 'VMware Photon Linux 3.0 (x86_64)' from 'https://dl.bintray.com/vmware/photon_release_3.0_x86_64'
curl#7: Couldn't connect to server
Error: Failed to synchronize cache for repo 'VMware Photon Extras 3.0 (x86_64)' from 'https://dl.bintray.com/vmware/photon_extras_3.0_x86_64'
curl#7: Couldn't connect to server
Error: Failed to synchronize cache for repo 'VMware Photon Linux 3.0 (x86_64) Updates' from 'https://dl.bintray.com/vmware/photon_updates_3.0_x86_64'
Error(1030) : The operation would result in removing the protected package : tdnf
Refreshing metadata for: 'VMware Photon Linux 3.0 (x86_64)'
Disabling Repo: 'VMware Photon Linux 3.0 (x86_64)'
Refreshing metadata for: 'VMware Photon Extras 3.0 (x86_64)'
Disabling Repo: 'VMware Photon Extras 3.0 (x86_64)'
Refreshing metadata for: 'VMware Photon Linux 3.0 (x86_64) Updates'
Disabling Repo: 'VMware Photon Linux 3.0 (x86_64) Updates'
The command '/bin/sh -c tdnf remove -y toybox && tdnf install -y tar findutils attr util-linux python3 python3-pip python3-setuptools git' returned a non-zero code: 6
```

**Expected behavior**
I expected to be able to build the solution. 

**Environment you are running Tern on**
Enter all that apply
Docker Desktop (Windows) 2.2.0.4 
- Container OS: Linux
- Python version: 3.82

**Please attach files if they exist**
n/a

**Comment by rnjudge** [comment] 2020-04-01 15:59
FWIW as a data point, I was not able to reproduce this issue on my Ubuntu VM even when running `docker build --no-cache -t ternd .` in order to force a metadata update (i.e. re-pulling the RPMs to install)

**Comment by rnjudge** [comment] 2020-04-01 20:35
Closing as we determined this was an issue with the local docker client not being able to connect externally rather than an issue with Tern (or Photon).

**Closed by rnjudge** 2020-04-01 20:35 UTC
