### ISSUE TITLE
After running tern, the /dev/null file missed

### ISSUE THREAD

**Issue by bitsf** [vmware/tern#463] opened 2019-09-27 09:12 UTC
**Describe the bug**
Hi,
  I just trying this, with pip3 install tern on ubuntu, after run "tern -l report -i photon:2.0", and find my /dev/null is overwrite. This is terrible

**To Reproduce**
env: ubuntu--0 4.18.0-10-generic, docker 18.09.2
1. pip3 install tern
2. tern -l report -i photon:2.0 | tee r.log, (actually it's another private image based on this)
3. because time it's long, so I stopped with Ctl+C
4. tern -l report -i busybox, errors with delete temp folder
4. manually run 'rm -rf ./temp', but still failed, because some file's permission, even root can't delete directly
5. and some command may failed
![image](https://user-images.githubusercontent.com/188115/65757129-186a6980-e149-11e9-8c55-7b3f1ca64358.png)
![image](https://user-images.githubusercontent.com/188115/65757183-38019200-e149-11e9-9b09-af8701fd63c2.png)
6. when disconnect ssh, it will never connect again with error 
"ssh_exchange_identification: read: Connection reset by peer"

**Error in terminal**
![image](https://user-images.githubusercontent.com/188115/65757129-186a6980-e149-11e9-8c55-7b3f1ca64358.png)

**Expected behavior**
/dev/null should not be deleted, no matter what I test with tern. And maybe some other important file also be deleted that I didn't know.

**Environment you are running Tern on**
Enter all that apply
- Output of 'tern --version'
0.4.0
- Operating System (Linux Distro and version or Mac or Windows)
ubuntu 18.0
- Vagrant file
- Container OS
docker 18.09
- Python version (3.6 or higher)
3.7
- Cloud environment (AWS, Azure, GCP)
Vsphere

**Please attach files if they exist**

**Comment by nishakm** [comment] 2019-09-27 13:37
@bitsf I'll check it out.

**Comment by nishakm** [comment] 2019-09-27 13:45
@bitsf Do you happen to have a tern.log file so I can see where you ctrl+c'd?

**Comment by nishakm** [comment] 2019-09-27 14:05
> @bitsf Do you happen to have a tern.log file so I can see where you ctrl+c'd?

I tried this on the vagrant VM (which already has tern installed using pip3).

I suspect the ctrl+c happened over here:
`2019-09-27 13:42:36,503 - DEBUG - rootfs - Running command: sudo unshare -pf --mount-proc=/home/vagrant/temp/mergedir/proc chroot temp/mergedir /usr/bin/bash -c tdnf check-update > /dev/null && pkgs=`tdnf list installed | cut -f1 -d"."` && for p in $pkgs; do tdnf info $p | head -9 | tail -1 | cut -f2-3 -d":" | xargs; done`

It takes a long time because photon2.0 is old and the indexes are empty. So in order to list packages that are installed, it has to first populate the indexes all the way up to whatever photon3 is at this time.

I tried to ctrl+c here and I see and I can still access `/dev/null` for the host.

Now, the root filesystem for the image also has a `/dev/null` which exists in the temp directory:
```
vagrant@ubuntu-bionic:~/temp/45bba0b8a86dcc14280211a0a15a4b3a14797603b3b5457cfd295fc118150252/contents/dev$ ls -al | grep null
crw-rw-rw-  1 root    root      1,   3 Sep 27 13:40 null
```
This is owned by root. So root should be able to delete it but it cannot.

So I've recreated the error, but the host's /dev/null is definitely not gone.

**Comment by nishakm** [comment] 2019-09-27 17:36
The problem is that tern mounts the container filesystem and runs the package manager commands on it. if the user sends a keyboard interrupt while it is doing this, then the temp folder is still mounted and live. So it cannot be removed until it is unmounted. If the user exists out of this session and tries to log back in again using ssh, the VM will not allow them because there is a live mount on the VM. The solution is to unmount the filesystem before exiting out of the session.

```
$ python3
Python 3.6.8 (default, Aug 20 2019, 17:12:48) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from tern.utils import rootfs
>>> rootfs.undo_mount()
>>> rootfs.unmount_rootfs()
>>> 
```

However, many users will have a tendency to send a keyboard interrupt while the filesystem is mounted, and there is no way for tern to recover from this kind of exception. So I will file a feature request to detect a keyboard interrupt while running in mounted mode and unmount gracefully when this happens

**Comment by nishakm** [comment] 2019-09-27 17:48
Closing issue and `/dev/null` is not getting deleted.

**Closed by nishakm** 2019-09-27 17:48 UTC
Labels: bug

**Comment by rnjudge** [comment] 2019-09-28 00:15
I was able to re-create this issue by doing the following on my working VM:

1. ctrl-c in the middle of running tern
2. `$ python3`
``` 
>>> from tern.utils import rootfs
>>> rootfs.undo_mount()
>>> rootfs.unmount_rootfs()
```
3. exit out of the python environment
4. `$ rm -rf temp`

Shutting down completely and re-starting my VM fixed the issue (I was blocked from just re-starting) but most of the /dev sub directories were missing before the restart.

**Comment by nishakm** [comment] 2019-09-30 13:23
The reason why /dev/null is getting deleted is because /dev is still mounted in the temp directory...which you then delete recursively. This gets fixed when you reboot, but if it doesn't do it reliably, then you have to keep doing the unmount until there is no mountpoint to unmount.

**Comment by bitsf** [comment] 2019-10-08 06:51
I think maybe you can mount file system with readonly permission, which would be much safer, or maybe other folder exept /dev would also be modified by mistake.

**Comment by nishakm** [comment] 2019-10-08 12:44
Unfortunately, to list the packages, you need to mount /proc, /sys and /dev as the package manager reads and writes to all of these. Docker does this as well. Just not in your home directory. See the fix for this issue here: https://github.com/vmware/tern/pull/467
